import React from 'react';
import { DataSource } from '../../types';
import { Sparkles, Eye, BookOpen } from 'lucide-react';

interface DataSourceBadgeProps {
  source: DataSource;
  size?: 'sm' | 'md';
  className?: string;
}

export const DataSourceBadge: React.FC<DataSourceBadgeProps> = ({
  source,
  size = 'md',
  className = ''
}) => {
  const isSmall = size === 'sm';
  const sizeClasses = isSmall
    ? 'text-[10px] px-1.5 py-0.5 gap-1'
    : 'text-xs px-2.5 py-1 gap-1.5 font-medium';

  if (source === 'SIMULATED') {
    return (
      <span
        title="Simulated reading generated by stochastic mathematical model"
        className={`inline-flex items-center rounded-md bg-purple-50 text-purple-700 border border-purple-200 uppercase tracking-wider ${sizeClasses} ${className}`}
      >
        <Sparkles className={isSmall ? 'w-2.5 h-2.5 text-purple-500' : 'w-3.5 h-3.5 text-purple-500'} />
        <span>Simulated</span>
      </span>
    );
  }

  if (source === 'OBSERVED') {
    return (
      <span
        title="Field reading recorded using physical measurement equipment or manual observation"
        className={`inline-flex items-center rounded-md bg-emerald-50 text-emerald-800 border border-emerald-300 uppercase tracking-wider ${sizeClasses} ${className}`}
      >
        <Eye className={isSmall ? 'w-2.5 h-2.5 text-emerald-600' : 'w-3.5 h-3.5 text-emerald-600'} />
        <span>Observed</span>
      </span>
    );
  }

  return (
    <span
      title="Imported research repository or municipal baseline study dataset"
      className={`inline-flex items-center rounded-md bg-blue-50 text-blue-700 border border-blue-200 uppercase tracking-wider ${sizeClasses} ${className}`}
    >
      <BookOpen className={isSmall ? 'w-2.5 h-2.5 text-blue-500' : 'w-3.5 h-3.5 text-blue-500'} />
      <span>Research Data</span>
    </span>
  );
};
