import { ResearchTopic } from '../types';

export const RESEARCH_TOPICS: ResearchTopic[] = [
  {
    id: 'topic-1',
    number: 1,
    title: 'What is Urban Noise Pollution?',
    summary: 'Understanding unwanted or harmful ambient outdoor sound created by human activity in urban settlements.',
    keyPoints: [
      'Noise pollution is defined by environmental health agencies as unwanted or detrimental outdoor sound generated by anthropogenic activity.',
      'Unlike atmospheric pollutants (such as PM2.5 or ozone), acoustic energy leaves no chemical residue in air, soil, or water.',
      'Its transience often leads policymakers to underestimate its long-term physiological and psychological toll on urban populations.',
      'Urban acoustical environments (soundscapes) consist of biophony (biological sounds), geophony (natural physical sounds), and anthrophony (human-generated acoustic emissions).'
    ],
    details: [
      'In high-density metropolises, sound pressure levels routinely exceed statutory safety limits, resulting in chronic exposure for millions of residents.',
      'The World Health Organization (WHO) classifies environmental noise as one of the top environmental hazards to physical and mental health and well-being in urban habitats.',
      'Acoustic energy diminishes according to the inverse-square law in free fields, but urban canyons (street facades flanked by tall buildings) reflect and trap acoustic waves, creating high reverberant sound fields.'
    ],
    metricsOrStandards: [
      { label: 'Ambient Noise Limit (WHO Sleep)', value: '45 dB(A) Lnight', notes: 'Recommended limit outside bedrooms to avoid sleep disruption' },
      { label: 'Daytime Urban Health Target (WHO)', value: '53 dB(A) Lden', notes: 'Road traffic noise exposure guideline' }
    ],
    citations: [
      {
        title: 'Environmental Noise Guidelines for the European Region',
        organization: 'World Health Organization (WHO) Regional Office for Europe',
        year: 2018,
        documentRef: 'ISBN 978 92 890 5356 3',
        url: 'https://www.who.int/europe/publications/i/item/9789289053563'
      },
      {
        title: 'Guidelines for Community Noise',
        organization: 'World Health Organization (WHO)',
        year: 1999,
        documentRef: 'Edited by B. Berglund, T. Lindvall, D. Schwela',
        url: 'https://www.who.int/docstore/peh/noise/guidelines2.html'
      }
    ]
  },
  {
    id: 'topic-2',
    number: 2,
    title: 'Major Sources of Urban Noise',
    summary: 'Categorization of anthropogenic acoustic generators across vehicular, rail, aviation, industrial, construction, and community domains.',
    keyPoints: [
      'Road Transportation: The single largest contributor to urban noise exposure, dominated by engine acceleration, exhaust systems, and tire-pavement friction at higher speeds (>45 km/h).',
      'Construction & Civil Infrastructure: Transient yet intense acoustic peaks generated by hydraulic rock breakers, diesel generators, pile drivers, and heavy transit mixers.',
      'Industrial & Fabrication Sites: Machinery, cooling towers, ventilation chillers, and material handling.',
      'Commercial & Community Sound: Public address systems, retail loudspeakers, market commotion, and portable diesel generator sets during power interruptions.'
    ],
    details: [
      'In developing urban centers, frequent vehicular horn usage (ranging from 90 dB to 110 dB at 1 meter) elevates baseline urban soundscapes into acute distress zones.',
      'Acoustic source partitioning studies demonstrate that tire-pavement interaction sound overtakes powertrain noise above 40-50 km/h for passenger cars and 60 km/h for heavy commercial trucks.'
    ],
    citations: [
      {
        title: 'Report on Ambient Noise Monitoring Network in 7 Metros',
        organization: 'Central Pollution Control Board (CPCB), Ministry of Environment, Forest and Climate Change, Govt. of India',
        year: 2020,
        documentRef: 'National Ambient Noise Monitoring Network (NANMN) Technical Bulletin'
      }
    ]
  },
  {
    id: 'topic-3',
    number: 3,
    title: 'Environmental and Human Health Impacts',
    summary: 'Distinction between auditory damage and chronic non-auditory systemic pathophysiology.',
    keyPoints: [
      'Auditory Damage: Noise-Induced Hearing Loss (NIHL) and acoustic trauma typically occur after sustained exposure above 85 dB(A) or acute bursts above 120 dB(A).',
      'Cardiovascular Morbidity: Chronic noise triggers neuroendocrine stress pathways (hypothalamic-pituitary-adrenal axis), releasing cortisol and adrenaline, leading to hypertension and ischemic heart disease.',
      'Sleep Architecture Fragmentation: Nighttime acoustic events as low as 40-45 dB(A) induce cortical awakenings, decrease slow-wave (deep) and REM sleep, and impair immune recovery.',
      'Cognitive Impairment in Children: Chronic exposure in school zones demonstrably degrades reading comprehension, speech perception, and sustained attentional focus.'
    ],
    details: [
      'Epidemiological evidence synthesis by the WHO demonstrates a relative risk increase for ischemic heart disease of 1.08 per 10 dB increase in road traffic noise above 53 dB Lden.',
      'Non-auditory physiological effects do not adapt over time; the autonomic nervous system responds to noise triggers even during unconscious deep sleep.'
    ],
    citations: [
      {
        title: 'Burden of Disease from Environmental Noise: Quantification of Healthy Life Years Lost in Europe',
        organization: 'World Health Organization & Joint Research Centre (JRC)',
        year: 2011,
        documentRef: 'WHO Regional Office for Europe, Copenhagen'
      }
    ]
  },
  {
    id: 'topic-4',
    number: 4,
    title: 'Noise Measurement Principles & Metrics',
    summary: 'Acoustic physics, logarithmic scales, frequency weighting filters, and standardized temporal integration parameters.',
    keyPoints: [
      'Sound Pressure Level (SPL): Measured in decibels (dB), a logarithmic ratio of measured sound pressure P to reference pressure P0 (20 micropascals in air, the human auditory threshold at 1 kHz).',
      'A-Weighting (dBA): An electronic filter approximating the human ear frequency sensitivity (attenuating low and very high frequencies per Fletcher-Munson equal-loudness contours).',
      'Equivalent Continuous Sound Level (Leq): The steady sound pressure level over a specified duration T containing the identical total acoustic energy as the actual fluctuating signal.',
      'Day-Evening-Night Level (Lden): Weighted 24-hour composite metric penalizing evening (+5 dB) and night (+10 dB) emissions to model heightened human annoyance.'
    ],
    details: [
      'Formula: Lp = 20 * log10(P / P0) dB, where P0 = 20 μPa.',
      'Statistical percentiles (L10, L90): L10 represents the noise level exceeded for 10% of the measurement duration (indicative of traffic peaks); L90 represents the level exceeded for 90% of the period (ambient background floor).'
    ],
    citations: [
      {
        title: 'ISO 1996-1:2016: Acoustics — Description, measurement and assessment of environmental noise — Part 1: Basic quantities and assessment procedures',
        organization: 'International Organization for Standardization (ISO)',
        year: 2016,
        documentRef: 'ISO 1996-1:2016'
      }
    ]
  },
  {
    id: 'topic-5',
    number: 5,
    title: 'Urban Noise Patterns & Spatial Dynamics',
    summary: 'Diurnal cycles, canyon reverberation, geometric attenuation, and meteorological effects on sound propagation.',
    keyPoints: [
      'Diurnal Bimodal Distribution: Urban soundscapes mirror vehicular rush hours, exhibiting morning (08:00-10:30) and evening (17:30-20:30) acoustic summits.',
      'Street Canyon Effect: In narrow urban corridors lined by vertical masonry facades, multiple specular reflections trap acoustic energy, increasing sound pressure by 3 to 6 dB relative to open terrain.',
      'Atmospheric Refraction: Daytime thermal gradients bend sound upward away from ground receptors; nighttime temperature inversions bend acoustic rays downward, propagating noise over greater distances.'
    ],
    details: [
      'Meteorological variables (relative humidity, wind vector gradients, air temperature) substantially alter acoustic attenuation, particularly for frequencies above 1 kHz.'
    ],
    citations: [
      {
        title: 'Urban Sound Environment',
        organization: 'Academic Press / Elsevier',
        year: 2006,
        documentRef: 'Kang, J. Urban Sound Environment. CRC Press / Taylor & Francis'
      }
    ]
  },
  {
    id: 'topic-6',
    number: 6,
    title: 'Monitoring Technologies & Sensor Architectures',
    summary: 'Class 1/2 laboratory instrumentation versus emerging edge-computing IoT sensor nodes.',
    keyPoints: [
      'Reference Class 1 / Class 2 Instruments: Precision condenser microphones certified under IEC 61672-1 standards with tight frequency tolerances and routine acoustic field calibration.',
      'IoT Edge Nodes: Micro-Electro-Mechanical Systems (MEMS) digital microphones (e.g. INMP441) interfaced with microcontrollers (ESP32, STM32) performing onboard Fast Fourier Transforms (FFT).',
      'Crowdsourcing & Smartphone Sensing: Low barrier to entry, but plagued by non-linear automatic gain control (AGC), directional orientation errors, and uncalibrated microphone capsules.'
    ],
    details: [
      'While IoT MEMS nodes are cost-effective for dense spatial telemetry, temperature drift and humidity degradation require automated cross-calibration routines against reference stations.'
    ],
    citations: [
      {
        title: 'IEC 61672-1:2013: Electroacoustics - Sound level meters - Part 1: Specifications',
        organization: 'International Electrotechnical Commission (IEC)',
        year: 2013,
        documentRef: 'IEC Standard Catalogue'
      }
    ]
  },
  {
    id: 'topic-7',
    number: 7,
    title: 'Noise Control Strategies & Mitigation',
    summary: 'Acoustic hierarchy of controls: Source elimination, transmission path interception, and receptor shielding.',
    keyPoints: [
      'Source Controls: Porous asphalt / low-noise road surfaces (reducing tire roar by 3-5 dB), electric bus fleet transition, and low-frequency variable speed limits.',
      'Transmission Path Controls: Acoustic barriers (transparent polycarbonates or earth berms), dense evergreen vegetation green belts (providing acoustic scattering and psychological relief).',
      'Urban Planning Controls: Mixed-use acoustic zoning, building facade orientation, and statutory buffer distances between arterial freight corridors and residential sectors.'
    ],
    details: [
      'Vegetation belts require at least 10-15 meters of dense foliage depth to yield measurable physical attenuation (1-3 dB), though their psychological masking effect substantially mitigates annoyance.'
    ],
    citations: [
      {
        title: 'Noise Barrier Design Handbook',
        organization: 'Federal Highway Administration (FHWA), US Department of Transportation',
        year: 2011,
        documentRef: 'Report No. FHWA-HEP-17-005'
      }
    ]
  },
  {
    id: 'topic-8',
    number: 8,
    title: 'The Smart City Approach',
    summary: 'Transitioning from periodic manual sound audits to dynamic, real-time spatial digital twins.',
    keyPoints: [
      'Real-Time Spatial Awareness: High-density sensor telemetry feeding GIS heatmaps allows city engineers to identify emerging acoustic hotspots instantaneously.',
      'Dynamic Traffic Management: Adaptive signal phasing and intelligent routing diverting heavy freight away from noise-saturated corridors or sensitive healthcare perimeters.',
      'Automated Regulatory Enforcement: Automated logging of anomalous acoustic spikes exceeding municipal curfews to dispatch municipal compliance inspectors.'
    ],
    details: [
      'Digital twins of urban soundscapes allow municipal planners to simulate the acoustic consequences of new highway overpasses or zoning alterations prior to physical construction.'
    ],
    citations: [
      {
        title: 'Smart Cities and the Soundscape Approach',
        organization: 'Journal of the Acoustical Society of America (JASA)',
        year: 2018,
        documentRef: 'Aletta, F., et al., J. Acoust. Soc. Am. 143, 1787'
      }
    ]
  },
  {
    id: 'topic-9',
    number: 9,
    title: 'Current Prototype Limitations',
    summary: 'Transparent technical boundaries of the current educational implementation.',
    keyPoints: [
      'No Physical Hardware in Current Version: This web prototype operates on stochastic simulation models and imported research/observed datasets.',
      'Acoustic Source Unclassification: Without multi-microphone beamforming arrays or trained audio event classification neural networks, precise physical causes remain rule-based inferences.',
      'Spatial Resolution: Map interpolation across discrete points provides illustrative gradients rather than millimeter-level 3D ray-tracing simulations.'
    ],
    details: [
      'Academic integrity requires transparent acknowledgment that demo values illustrate dashboard mechanics and software workflows, rather than real-time physical atmospheric measurements.'
    ],
    citations: [
      {
        title: 'Academic Integrity and Environmental Sensor Prototyping Standards',
        organization: 'Environmental Studies (EVS) Research Curriculum',
        year: 2026,
        documentRef: 'EVS Environmental Noise & Urban Ecology Guidelines'
      }
    ]
  },
  {
    id: 'topic-10',
    number: 10,
    title: 'Future Research Scope & IoT Architecture',
    summary: 'Roadmap for hardware deployment, edge machine learning, and acoustic classification.',
    keyPoints: [
      'Edge Machine Learning: Integrating tinyML models (e.g. MobileNet-based acoustic classifier) onto ESP32-S3 microcontrollers to categorize sound sources (horns vs jackhammers vs engine idle) locally without streaming raw audio.',
      'Privacy-Preserving Edge Processing: By computing 1/3-octave band SPL and acoustic feature vectors on edge microcontrollers, ambient audio is never recorded or transmitted, protecting citizen privacy.',
      'Predictive Spatio-Temporal Forecasting: Utilizing Graph Neural Networks (GNN) and LSTM networks to forecast weekend or holiday noise surges from weather and traffic telemetry.'
    ],
    details: [
      'The envisioned hardware pipeline: Calibrated I2S MEMS microphone -> ESP32 microcontroller running onboard FFT -> TLS-encrypted MQTT over Wi-Fi/4G -> Supabase PostgreSQL DB -> NoiseWatch Live UI.'
    ],
    citations: [
      {
        title: 'Acoustic Sensor Networks for Environmental Noise Monitoring: A Review',
        organization: 'Sensors Journal (MDPI)',
        year: 2020,
        documentRef: 'Sensors 2020, 20(4), 1038'
      }
    ]
  }
];
